Task 3
l-golofastov/formal-lang-course pull request #4
Opened 2023-10-16 21:33 UTC by l-golofastov

Извиняюсь за столь позднюю сдачу :(

2023-10-19 08:10 UTC, EgorOrachyov requested changes

2023-10-19 08:10 UTC, EgorOrachyov commented on project/work_with_graph.py
> +def make_regular_path_query(regex, graph, start_nodes=None, final_nodes=None):
Work_with_graph -- больше похоже на модуль с утилитами. А вот сам rpq запрос - это лучше в отдельный модуль.
Плюс, я бы изменил название, тк make_* больше на создание/конструирование объекта похоже, а тут выполнение запроса.
Более того rpq - это просто запрос с регулярными ограничениями, а у ВАС здесь конкретный алгоритм, т.е. лучше что-то вроде `def rgq_tensor` и тд, чтобы конкретный алгоритм в названии был отражен, например.

2023-10-22 11:20 UTC, l-golofastov commented on project/work_with_graph.py
> +def make_regular_path_query(regex, graph, start_nodes=None, final_nodes=None):
Поправил, изменив немного структуру проекта и нейминг.

2023-10-25 08:44 UTC, EgorOrachyov approved these changes

2023-10-25 09:12 UTC, merged