Task 6
l-golofastov/formal-lang-course pull request #6
Opened 2023-11-20 19:41 UTC by l-golofastov

Преобразование КС грамматики в ОНФХ и чтение из файла.

Благодарю! :)

2023-11-22 08:29 UTC, EgorOrachyov requested changes

2023-11-22 08:29 UTC, EgorOrachyov commented on project/cfg_utils.py
> +from pyformlang.cfg import CFG
Избегайте использования слова utils в названиях фалов, это паразит, который смысла недобавляет. Названия cfg.py вполне бы хватило

2023-11-22 08:29 UTC, EgorOrachyov commented on project/cfg_utils.py
> +def get_weak_chomsky_normal_form(grammar):
`get` это что то ближе к получению проперти или стейта, а здесь вы именно преобразование/конвертацию делаете, поэтому cfg_to_wcfg (например), было бы более осмысленным названием

2023-11-23 19:39 UTC, l-golofastov commented on project/cfg_utils.py
> +from pyformlang.cfg import CFG
Поправил

2023-11-23 19:40 UTC, l-golofastov commented on project/cfg_utils.py
> +def get_weak_chomsky_normal_form(grammar):
Изменил

2023-11-27 08:35 UTC, EgorOrachyov approved these changes

2023-11-27 11:23 UTC, merged